# Numpy

In [5]:
import numpy as np

numbers = [1, 2, 3, 4]

arr = np.array([1, 2, 3, 4])

arr2 = np.array([[1, 2],[3, 4]])

print(arr2)



[[1 2]
 [3 4]]


In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [7]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [9]:
print(np.ones([5,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [12]:
print(np.linspace(0, 5, 5))

[0.   1.25 2.5  3.75 5.  ]


In [13]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])

arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape

(2, 3)

In [ ]:
arr2.size # No.elements 

6

In [ ]:
arr2.dtype # the data type

dtype('int64')

In [ ]:
arr2.ndim # No.dimension

2

In [18]:
arr3 = np.array([1, 2, 3], dtype=np.float32)

arr3.dtype

dtype('float32')

In [22]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[-1])

7


In [23]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr5[1,1]

np.int64(5)

In [24]:
arr5[arr5 > 4]

array([5, 6, 7, 8, 9])

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
a + b # array arithmatics 

array([5, 7, 9])

In [27]:
a * 10

array([10, 20, 30])

In [30]:
c = np.array([10, 20, 30, 40])

In [ ]:
c.mean() # aggregate functions mean, sum 

np.float64(25.0)

In [32]:
c.sum()

np.int64(100)

In [33]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [ ]:
d.reshape(3, 4) # reshape the size of the array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
d.reshape(-1,2) # -1 means dynamically configure the number of rows

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
np.random.rand(3)

array([0.49208255, 0.03014329, 0.96881154])