# NumPy

**What is NumPy?**

NumPy (Numerical Python) is the core library for numerical computing in Python. It provides:

Fast multi-dimensional arrays

Mathematical operations on arrays

Linear algebra, statistics, and random number tools

**Why NumPy?**

Much faster than Python lists

Memory efficient

Foundation for Pandas, SciPy, Scikit-learn, TensorFlow

## Install NumPy

In [2]:
#!pip install numpy

## Import NumPy

In [3]:
import numpy as np

## NumPy Arrays vs Python Lists

**Python List**

In [9]:
numbers = [1, 2, 3, 4]
numbers * 2

[1, 2, 3, 4, 1, 2, 3, 4]

**NumPy Array**

In [10]:
arr = np.array([1, 2, 3, 4])
arr * 2

array([2, 4, 6, 8])

Key difference: NumPy applies operations element-wise.

## Creating NumPy Arrays

**From Python Lists**

In [27]:
arr1 = np.array([10, 20, 30])

In [22]:
arr1

array([10, 20, 30])

In [23]:
arr2 = np.array([[1, 2], [3, 4]])

In [24]:
arr2

array([[1, 2],
       [3, 4]])

**Built-in Creation Functions**

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [19]:
np.eye(4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Ranges**

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [43]:
# Generates 5 evenly spaced numbers from 0 to 1 (inclusive)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# --- LINSPACE vs ARANGE ---

# Use linspace when you know HOW MANY points you want.
# "Give me exactly 5 numbers between 0 and 1 (includes 1.0)"
# Result: [0.  , 0.25, 0.5 , 0.75, 1.  ]
# np.linspace(0, 1, 5)

# Use arange when you know the STEP SIZE you want.
# "Give me numbers from 0 up to 1, jumping by 0.25 (excludes 1.0)"
# Result: [0.  , 0.25, 0.5 , 0.75]
# np.arange(0, 1, 0.25)

# KEY RULE:
# Linspace = Count-based (includes the end)
# Arange   = Step-based  (excludes the end)

## Array Properties

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
arr.shape # Dimensions

(2, 3)

In [31]:
arr.ndim # Number of axes

2

In [32]:
arr.size # Total elements

6

In [33]:
arr.dtype # Data type

dtype('int64')

## Data Types (dtype)

In [35]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [36]:
np.array([1.5, 2.7]).dtype

dtype('float64')

In [46]:
# Creates an array of floating-point numbers (1.0, 2.0, 3.0) 
# dtype=np.float32 forces the numbers to be decimals instead of integers
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

**Type conversion:**

In [41]:
arr = np.array([1, 2, 3])

In [42]:
arr.astype(float)

array([1., 2., 3.])

## Indexing & Slicing

**1D Arrays**

In [47]:
arr = np.array([10, 20, 30, 40, 50])

In [48]:
arr[0]

np.int64(10)

In [49]:
arr[-1]

np.int64(50)

In [50]:
arr[1:4]

array([20, 30, 40])

**2D Arrays**

In [52]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [53]:
matrix[0, 1]

np.int64(2)

In [54]:
matrix[:, 1]

array([2, 5, 8])

In [55]:
matrix[1, :]

array([4, 5, 6])

## Boolean Indexing

In [56]:
arr = np.array([5, 10, 15, 20, 25])

In [57]:
arr[arr > 15]

array([20, 25])

In [58]:
arr[arr % 10 == 0]

array([10, 20])

## Mathematical Operations

**Element-wise Operations**

In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [61]:
a + b

array([5, 7, 9])

In [62]:
a - b

array([-3, -3, -3])

In [63]:
a * b

array([ 4, 10, 18])

In [64]:
a / b

array([0.25, 0.4 , 0.5 ])

**Scalar Operations**

In [65]:
a * 10

array([10, 20, 30])

In [66]:
a + 5

array([6, 7, 8])

## Aggregation Functions

In [67]:
arr = np.array([10, 20, 30, 40])

In [68]:
arr.sum()

np.int64(100)

In [69]:
arr.mean()

np.float64(25.0)

In [70]:
arr.min()

np.int64(10)

In [71]:
arr.max()

np.int64(40)

In [72]:
arr.std()

np.float64(11.180339887498949)

**Along Axes**

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [74]:
matrix.sum(axis=0) # Columns

array([12, 15, 18])

In [75]:
matrix.sum(axis=1) # Rows

array([ 6, 15, 24])

## Reshaping Arrays

In [79]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
arr.reshape(-1, 2) # Automatic rows

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## Stacking & Splitting

**Stacking**

In [86]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [87]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [84]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

**Splitting**

In [94]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.split(arr, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

## Random Numbers

In [96]:
np.random.rand(3)

array([0.78748896, 0.85124053, 0.74222215])

In [97]:
np.random.rand(2, 3)

array([[0.62210114, 0.78801898, 0.36713342],
       [0.38657146, 0.45272805, 0.04892597]])

In [100]:
# Generates 10 random integers between 0 (inclusive) and 100 (exclusive)
# 0: Minimum | 100: Maximum | size=10: How many numbers to create
np.random.randint(0, 100, size=10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74], dtype=int32)

In [101]:
# Sets a "starting point" for random numbers so they are the same every time you run the code
# "42" is just a common choice; any number works as long as it stays the same
np.random.seed(42)

## Broadcasting

In [109]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Broadcasting: The smaller array [10, 20, 30] is added to EVERY row of the matrix
# Row 1: [1+10, 2+20, 3+30] -> [11, 22, 33]
# Row 2: [4+10, 5+20, 6+30] -> [14, 25, 36]
# Result: [[11, 22, 33], [14, 25, 36]]
arr + np.array([10, 20, 30])

array([[11, 22, 33],
       [14, 25, 36]])

## Linear Algebra Basics

In [105]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [106]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [103]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [104]:
a @ b

array([[19, 22],
       [43, 50]])

In [107]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [108]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Performance Comparison (Loop vs NumPy)

In [112]:
import time

In [113]:
size = 1_000_000
python_list = list(range(size))
np_array = np.arange(size)

In [116]:
# Record the current time in seconds (the "start" timestamp)
start = time.time()
# A list comprehension: doubles every number in a standard Python list
[x * 2 for x in python_list]
# Subtract the start time from the current time to get the "elapsed time"
# This tells you exactly how many seconds the operation took
time.time() - start

0.18784475326538086

In [117]:
start = time.time()
np_array * 2
time.time() - start

0.006582498550415039